### ISSUE TITLE
bug report fix

### ISSUE THREAD

**Issue by BAILEYMCQ1997** [BAILEYMCQ1997/sem#36]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BAILEYMCQ1997** [comment]
we need to fix this from being so long here

**Comment by NathanMurray1309** [comment]
This has been attempted. New branches created also with a few commits
